import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../providers/room_data_provider.dart';
import '../ui/screens/game_screen.dart';
import 'socket_io_client.dart';

class SocketMethods {
  final _socketClient = SocketIOClient.instance.socket;

  // This is the event generated by the client and server will listen to it.
  void createRoom(String nickName) {
    if (nickName.isNotEmpty) {
      _socketClient?.emit("createRoom", {
        'nickname': nickName,
      });
    }
  }

  // This is the event generated by the server and here the clinet is listening.
  void createRoomSuccess(BuildContext context) {
    _socketClient?.on('createRoomSuccess', (room) {
      Provider.of<RoomDataProvider>(context).updateRoomData(room);
      Navigator.push(context, GameScreen.route());
    });
  }
}
