import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:tictactoe/utils/show_snackbar.dart';

import '../providers/room_data_provider.dart';
import '../ui/screens/game_screen.dart';
import 'socket_io_client.dart';

class SocketMethods {
  final _socketClient = SocketIOClient.instance.socket;

  ///
  /// All Emitter
  ///

  // This is the event generated by the client and server will listen to it.
  void createRoom(String nickName) {
    if (nickName.isNotEmpty) {
      _socketClient?.emit("createRoom", {
        'nickname': nickName,
      });
    }
  }

  void joinRoom(String nickname, String roomId) {
    if (nickname.isNotEmpty) {
      _socketClient?.emit("joinRoom", {
        'nickname': nickname,
        'roomId': roomId,
      });
    }
  }

  ///
  /// All Listeners
  ///

  // This is the event generated by the server and here the clinet is listening.
  void createRoomSuccessListener(BuildContext context) {
    _socketClient?.on('createRoomSuccess', (room) {
      Provider.of<RoomDataProvider>(context, listen: false)
          .updateRoomData(room);
      Navigator.push(context, GameScreen.route());
    });
  }

  void joinRoomSuccessListener(BuildContext context) {
    _socketClient?.on('joinRoomSuccess', (room) {
      Provider.of<RoomDataProvider>(context, listen: false)
          .updateRoomData(room);
      Navigator.push(context, GameScreen.route());
    });
  }

  void errorOccurredListener(BuildContext context) {
    _socketClient?.on('errorOccurred', (error) {
      showSnackBar(context, error);
    });
  }
}
